
const getCountryFlag = function getCountryFlag(country: string) {
  country = country?.toLowerCase();
  const nations = countries.filter(v => {
    return v.name?.toLowerCase() === country || v.code?.toLowerCase() === country;
  });
  let image = null;
  if(nations.length > 0){
    image = require('./../assets/images/flag-icons-main/'+nations[0].flag_4X3);
  }
  return image;
};

export default getCountryFlag;

export const countries: { code: string; name: string; flag_4X3: string }[] = [
  { code: "af", name: "Afghanistan", flag_4X3: "flags/4x3/af.svg" },
  { code: "ax", name: "Aland Islands", flag_4X3: "flags/4x3/ax.svg" },
  { code: "al", name: "Albania", flag_4X3: "flags/4x3/al.svg" },
  { code: "dz", name: "Algeria", flag_4X3: "flags/4x3/dz.svg" },
  { code: "as", name: "American Samoa", flag_4X3: "flags/4x3/as.svg" },
  { code: "ad", name: "Andorra", flag_4X3: "flags/4x3/ad.svg" },
  { code: "ao", name: "Angola", flag_4X3: "flags/4x3/ao.svg" },
  { code: "ai", name: "Anguilla", flag_4X3: "flags/4x3/ai.svg" },
  { code: "aq", name: "Antarctica", flag_4X3: "flags/4x3/aq.svg" },
  { code: "ag", name: "Antigua and Barbuda", flag_4X3: "flags/4x3/ag.svg" },
  { code: "ar", name: "Argentina", flag_4X3: "flags/4x3/ar.svg" },
  { code: "am", name: "Armenia", flag_4X3: "flags/4x3/am.svg" },
  { code: "aw", name: "Aruba", flag_4X3: "flags/4x3/aw.svg" },
  { code: "ac", name: "Ascension Island", flag_4X3: "flags/4x3/ac.svg" },
  { code: "au", name: "Australia", flag_4X3: "flags/4x3/au.svg" },
  { code: "at", name: "Austria", flag_4X3: "flags/4x3/at.svg" },
  { code: "az", name: "Azerbaijan", flag_4X3: "flags/4x3/az.svg" },
  { code: "bs", name: "Bahamas", flag_4X3: "flags/4x3/bs.svg" },
  { code: "bh", name: "Bahrain", flag_4X3: "flags/4x3/bh.svg" },
  { code: "bd", name: "Bangladesh", flag_4X3: "flags/4x3/bd.svg" },
  { code: "bb", name: "Barbados", flag_4X3: "flags/4x3/bb.svg" },
  { code: "by", name: "Belarus", flag_4X3: "flags/4x3/by.svg" },
  { code: "be", name: "Belgium", flag_4X3: "flags/4x3/be.svg" },
  { code: "bz", name: "Belize", flag_4X3: "flags/4x3/bz.svg" },
  { code: "bj", name: "Benin", flag_4X3: "flags/4x3/bj.svg" },
  { code: "bm", name: "Bermuda", flag_4X3: "flags/4x3/bm.svg" },
  { code: "bt", name: "Bhutan", flag_4X3: "flags/4x3/bt.svg" },
  { code: "bo", name: "Bolivia", flag_4X3: "flags/4x3/bo.svg" },
  {
    code: "bq",
    name: "Bonaire, Sint Eustatius and Saba",
    flag_4X3: "flags/4x3/bq.svg",
  },
  { code: "ba", name: "Bosnia and Herzegovina", flag_4X3: "flags/4x3/ba.svg" },
  { code: "bw", name: "Botswana", flag_4X3: "flags/4x3/bw.svg" },
  { code: "bv", name: "Bouvet Island", flag_4X3: "flags/4x3/bv.svg" },
  { code: "br", name: "Brazil", flag_4X3: "flags/4x3/br.svg" },
  {
    code: "io",
    name: "British Indian Ocean Territory",
    flag_4X3: "flags/4x3/io.svg",
  },
  { code: "bn", name: "Brunei Darussalam", flag_4X3: "flags/4x3/bn.svg" },
  { code: "bg", name: "Bulgaria", flag_4X3: "flags/4x3/bg.svg" },
  { code: "bf", name: "Burkina Faso", flag_4X3: "flags/4x3/bf.svg" },
  { code: "bi", name: "Burundi", flag_4X3: "flags/4x3/bi.svg" },
  { code: "cv", name: "Cabo Verde", flag_4X3: "flags/4x3/cv.svg" },
  { code: "kh", name: "Cambodia", flag_4X3: "flags/4x3/kh.svg" },
  { code: "cm", name: "Cameroon", flag_4X3: "flags/4x3/cm.svg" },
  { code: "ca", name: "Canada", flag_4X3: "flags/4x3/ca.svg" },
  { code: "ic", name: "Canary Islands", flag_4X3: "flags/4x3/ic.svg" },
  { code: "es-ct", name: "Catalonia", flag_4X3: "flags/4x3/es-ct.svg" },
  { code: "es-pv", name: "Basque Country", flag_4X3: "flags/4x3/es-pv.svg" },
  { code: "ky", name: "Cayman Islands", flag_4X3: "flags/4x3/ky.svg" },
  {
    code: "cf",
    name: "Central African Republic",
    flag_4X3: "flags/4x3/cf.svg",
  },
  {
    code: "cefta",
    name: "Central European Free Trade Agreement",
    flag_4X3: "flags/4x3/cefta.svg",
  },
  { code: "ea", name: "Ceuta & Melilla", flag_4X3: "flags/4x3/ea.svg" },
  { code: "td", name: "Chad", flag_4X3: "flags/4x3/td.svg" },
  { code: "cl", name: "Chile", flag_4X3: "flags/4x3/cl.svg" },
  { code: "cn", name: "China", flag_4X3: "flags/4x3/cn.svg" },
  { code: "cx", name: "Christmas Island", flag_4X3: "flags/4x3/cx.svg" },
  { code: "cp", name: "Clipperton Island", flag_4X3: "flags/4x3/cp.svg" },
  { code: "cc", name: "Cocos (Keeling) Islands", flag_4X3: "flags/4x3/cc.svg" },
  { code: "co", name: "Colombia", flag_4X3: "flags/4x3/co.svg" },
  { code: "km", name: "Comoros", flag_4X3: "flags/4x3/km.svg" },
  { code: "ck", name: "Cook Islands", flag_4X3: "flags/4x3/ck.svg" },
  { code: "cr", name: "Costa Rica", flag_4X3: "flags/4x3/cr.svg" },
  { code: "hr", name: "Croatia", flag_4X3: "flags/4x3/hr.svg" },
  { code: "cu", name: "Cuba", flag_4X3: "flags/4x3/cu.svg" },
  { code: "cw", name: "Curaçao", flag_4X3: "flags/4x3/cw.svg" },
  { code: "cy", name: "Cyprus", flag_4X3: "flags/4x3/cy.svg" },
  { code: "cz", name: "Czech Republic", flag_4X3: "flags/4x3/cz.svg" },
  { code: "ci", name: "Côte d'Ivoire", flag_4X3: "flags/4x3/ci.svg" },
  {
    code: "cd",
    name: "Democratic Republic of the Congo",
    flag_4X3: "flags/4x3/cd.svg",
  },
  { code: "dk", name: "Denmark", flag_4X3: "flags/4x3/dk.svg" },
  { code: "dg", name: "Diego Garcia", flag_4X3: "flags/4x3/dg.svg" },
  { code: "dj", name: "Djibouti", flag_4X3: "flags/4x3/dj.svg" },
  { code: "dm", name: "Dominica", flag_4X3: "flags/4x3/dm.svg" },
  { code: "do", name: "Dominican Republic", flag_4X3: "flags/4x3/do.svg" },
  { code: "ec", name: "Ecuador", flag_4X3: "flags/4x3/ec.svg" },
  { code: "eg", name: "Egypt", flag_4X3: "flags/4x3/eg.svg" },
  { code: "sv", name: "El Salvador", flag_4X3: "flags/4x3/sv.svg" },
  { code: "gb-eng", name: "England", flag_4X3: "flags/4x3/gb-eng.svg" },
  { code: "gq", name: "Equatorial Guinea", flag_4X3: "flags/4x3/gq.svg" },
  { code: "er", name: "Eritrea", flag_4X3: "flags/4x3/er.svg" },
  { code: "ee", name: "Estonia", flag_4X3: "flags/4x3/ee.svg" },
  { code: "sz", name: "Eswatini", flag_4X3: "flags/4x3/sz.svg" },
  { code: "et", name: "Ethiopia", flag_4X3: "flags/4x3/et.svg" },
  { code: "eu", name: "Europe", flag_4X3: "flags/4x3/eu.svg" },
  { code: "fk", name: "Falkland Islands", flag_4X3: "flags/4x3/fk.svg" },
  { code: "fo", name: "Faroe Islands", flag_4X3: "flags/4x3/fo.svg" },
  {
    code: "fm",
    name: "Federated States of Micronesia",
    flag_4X3: "flags/4x3/fm.svg",
  },
  { code: "fj", name: "Fiji", flag_4X3: "flags/4x3/fj.svg" },
  { code: "fi", name: "Finland", flag_4X3: "flags/4x3/fi.svg" },
  { code: "fr", name: "France", flag_4X3: "flags/4x3/fr.svg" },
  { code: "gf", name: "French Guiana", flag_4X3: "flags/4x3/gf.svg" },
  { code: "pf", name: "French Polynesia", flag_4X3: "flags/4x3/pf.svg" },
  {
    code: "tf",
    name: "French Southern Territories",
    flag_4X3: "flags/4x3/tf.svg",
  },
  { code: "ga", name: "Gabon", flag_4X3: "flags/4x3/ga.svg" },
  { code: "es-ga", name: "Galicia", flag_4X3: "flags/4x3/es-ga.svg" },
  { code: "gm", name: "Gambia", flag_4X3: "flags/4x3/gm.svg" },
  { code: "ge", name: "Georgia", flag_4X3: "flags/4x3/ge.svg" },
  { code: "de", name: "Germany", flag_4X3: "flags/4x3/de.svg" },
  { code: "gh", name: "Ghana", flag_4X3: "flags/4x3/gh.svg" },
  { code: "gi", name: "Gibraltar", flag_4X3: "flags/4x3/gi.svg" },
  { code: "gr", name: "Greece", flag_4X3: "flags/4x3/gr.svg" },
  { code: "gl", name: "Greenland", flag_4X3: "flags/4x3/gl.svg" },
  { code: "gd", name: "Grenada", flag_4X3: "flags/4x3/gd.svg" },
  { code: "gp", name: "Guadeloupe", flag_4X3: "flags/4x3/gp.svg" },
  { code: "gu", name: "Guam", flag_4X3: "flags/4x3/gu.svg" },
  { code: "gt", name: "Guatemala", flag_4X3: "flags/4x3/gt.svg" },
  { code: "gg", name: "Guernsey", flag_4X3: "flags/4x3/gg.svg" },
  { code: "gn", name: "Guinea", flag_4X3: "flags/4x3/gn.svg" },
  { code: "gw", name: "Guinea-Bissau", flag_4X3: "flags/4x3/gw.svg" },
  { code: "gy", name: "Guyana", flag_4X3: "flags/4x3/gy.svg" },
  { code: "ht", name: "Haiti", flag_4X3: "flags/4x3/ht.svg" },
  {
    code: "hm",
    name: "Heard Island and McDonald Islands",
    flag_4X3: "flags/4x3/hm.svg",
  },
  { code: "va", name: "Holy See", flag_4X3: "flags/4x3/va.svg" },
  { code: "hn", name: "Honduras", flag_4X3: "flags/4x3/hn.svg" },
  { code: "hk", name: "Hong Kong", flag_4X3: "flags/4x3/hk.svg" },
  { code: "hu", name: "Hungary", flag_4X3: "flags/4x3/hu.svg" },
  { code: "is", name: "Iceland", flag_4X3: "flags/4x3/is.svg" },
  { code: "in", name: "India", flag_4X3: "flags/4x3/in.svg" },
  { code: "id", name: "Indonesia", flag_4X3: "flags/4x3/id.svg" },
  { code: "ir", name: "Iran", flag_4X3: "flags/4x3/ir.svg" },
  { code: "iq", name: "Iraq", flag_4X3: "flags/4x3/iq.svg" },
  { code: "ie", name: "Ireland", flag_4X3: "flags/4x3/ie.svg" },
  { code: "im", name: "Isle of Man", flag_4X3: "flags/4x3/im.svg" },
  { code: "il", name: "Israel", flag_4X3: "flags/4x3/il.svg" },
  { code: "it", name: "Italy", flag_4X3: "flags/4x3/it.svg" },
  { code: "jm", name: "Jamaica", flag_4X3: "flags/4x3/jm.svg" },
  { code: "jp", name: "Japan", flag_4X3: "flags/4x3/jp.svg" },
  { code: "je", name: "Jersey", flag_4X3: "flags/4x3/je.svg" },
  { code: "jo", name: "Jordan", flag_4X3: "flags/4x3/jo.svg" },
  { code: "kz", name: "Kazakhstan", flag_4X3: "flags/4x3/kz.svg" },
  { code: "ke", name: "Kenya", flag_4X3: "flags/4x3/ke.svg" },
  { code: "ki", name: "Kiribati", flag_4X3: "flags/4x3/ki.svg" },
  { code: "xk", name: "Kosovo", flag_4X3: "flags/4x3/xk.svg" },
  { code: "kw", name: "Kuwait", flag_4X3: "flags/4x3/kw.svg" },
  { code: "kg", name: "Kyrgyzstan", flag_4X3: "flags/4x3/kg.svg" },
  { code: "la", name: "Laos", flag_4X3: "flags/4x3/la.svg" },
  { code: "lv", name: "Latvia", flag_4X3: "flags/4x3/lv.svg" },
  { code: "lb", name: "Lebanon", flag_4X3: "flags/4x3/lb.svg" },
  { code: "ls", name: "Lesotho", flag_4X3: "flags/4x3/ls.svg" },
  { code: "lr", name: "Liberia", flag_4X3: "flags/4x3/lr.svg" },
  { code: "ly", name: "Libya", flag_4X3: "flags/4x3/ly.svg" },
  { code: "li", name: "Liechtenstein", flag_4X3: "flags/4x3/li.svg" },
  { code: "lt", name: "Lithuania", flag_4X3: "flags/4x3/lt.svg" },
  { code: "lu", name: "Luxembourg", flag_4X3: "flags/4x3/lu.svg" },
  { code: "mo", name: "Macau", flag_4X3: "flags/4x3/mo.svg" },
  { code: "mg", name: "Madagascar", flag_4X3: "flags/4x3/mg.svg" },
  { code: "mw", name: "Malawi", flag_4X3: "flags/4x3/mw.svg" },
  { code: "my", name: "Malaysia", flag_4X3: "flags/4x3/my.svg" },
  { code: "mv", name: "Maldives", flag_4X3: "flags/4x3/mv.svg" },
  { code: "ml", name: "Mali", flag_4X3: "flags/4x3/ml.svg" },
  { code: "mt", name: "Malta", flag_4X3: "flags/4x3/mt.svg" },
  { code: "mh", name: "Marshall Islands", flag_4X3: "flags/4x3/mh.svg" },
  { code: "mq", name: "Martinique", flag_4X3: "flags/4x3/mq.svg" },
  { code: "mr", name: "Mauritania", flag_4X3: "flags/4x3/mr.svg" },
  { code: "mu", name: "Mauritius", flag_4X3: "flags/4x3/mu.svg" },
  { code: "yt", name: "Mayotte", flag_4X3: "flags/4x3/yt.svg" },
  { code: "mx", name: "Mexico", flag_4X3: "flags/4x3/mx.svg" },
  { code: "md", name: "Moldova", flag_4X3: "flags/4x3/md.svg" },
  { code: "mc", name: "Monaco", flag_4X3: "flags/4x3/mc.svg" },
  { code: "mn", name: "Mongolia", flag_4X3: "flags/4x3/mn.svg" },
  { code: "me", name: "Montenegro", flag_4X3: "flags/4x3/me.svg" },
  { code: "ms", name: "Montserrat", flag_4X3: "flags/4x3/ms.svg" },
  { code: "ma", name: "Morocco", flag_4X3: "flags/4x3/ma.svg" },
  { code: "mz", name: "Mozambique", flag_4X3: "flags/4x3/mz.svg" },
  { code: "mm", name: "Myanmar", flag_4X3: "flags/4x3/mm.svg" },
  { code: "na", name: "Namibia", flag_4X3: "flags/4x3/na.svg" },
  { code: "nr", name: "Nauru", flag_4X3: "flags/4x3/nr.svg" },
  { code: "np", name: "Nepal", flag_4X3: "flags/4x3/np.svg" },
  { code: "nl", name: "Netherlands", flag_4X3: "flags/4x3/nl.svg" },
  { code: "nc", name: "New Caledonia", flag_4X3: "flags/4x3/nc.svg" },
  { code: "nz", name: "New Zealand", flag_4X3: "flags/4x3/nz.svg" },
  { code: "ni", name: "Nicaragua", flag_4X3: "flags/4x3/ni.svg" },
  { code: "ne", name: "Niger", flag_4X3: "flags/4x3/ne.svg" },
  { code: "ng", name: "Nigeria", flag_4X3: "flags/4x3/ng.svg" },
  { code: "nu", name: "Niue", flag_4X3: "flags/4x3/nu.svg" },
  { code: "nf", name: "Norfolk Island", flag_4X3: "flags/4x3/nf.svg" },
  { code: "kp", name: "North Korea", flag_4X3: "flags/4x3/kp.svg" },
  { code: "mk", name: "North Macedonia", flag_4X3: "flags/4x3/mk.svg" },
  {
    code: "gb-nir",
    name: "Northern Ireland",
    flag_4X3: "flags/4x3/gb-nir.svg",
  },
  {
    code: "mp",
    name: "Northern Mariana Islands",
    flag_4X3: "flags/4x3/mp.svg",
  },
  { code: "no", name: "Norway", flag_4X3: "flags/4x3/no.svg" },
  { code: "om", name: "Oman", flag_4X3: "flags/4x3/om.svg" },
  { code: "pk", name: "Pakistan", flag_4X3: "flags/4x3/pk.svg" },
  { code: "pw", name: "Palau", flag_4X3: "flags/4x3/pw.svg" },
  { code: "pa", name: "Panama", flag_4X3: "flags/4x3/pa.svg" },
  { code: "pg", name: "Papua New Guinea", flag_4X3: "flags/4x3/pg.svg" },
  { code: "py", name: "Paraguay", flag_4X3: "flags/4x3/py.svg" },
  { code: "pe", name: "Peru", flag_4X3: "flags/4x3/pe.svg" },
  { code: "ph", name: "Philippines", flag_4X3: "flags/4x3/ph.svg" },
  { code: "pn", name: "Pitcairn", flag_4X3: "flags/4x3/pn.svg" },
  { code: "pl", name: "Poland", flag_4X3: "flags/4x3/pl.svg" },
  { code: "pt", name: "Portugal", flag_4X3: "flags/4x3/pt.svg" },
  { code: "pr", name: "Puerto Rico", flag_4X3: "flags/4x3/pr.svg" },
  { code: "qa", name: "Qatar", flag_4X3: "flags/4x3/qa.svg" },
  { code: "cg", name: "Republic of the Congo", flag_4X3: "flags/4x3/cg.svg" },
  { code: "ro", name: "Romania", flag_4X3: "flags/4x3/ro.svg" },
  { code: "ru", name: "Russia", flag_4X3: "flags/4x3/ru.svg" },
  { code: "rw", name: "Rwanda", flag_4X3: "flags/4x3/rw.svg" },
  { code: "re", name: "Réunion", flag_4X3: "flags/4x3/re.svg" },
  { code: "bl", name: "Saint Barthélemy", flag_4X3: "flags/4x3/bl.svg" },
  {
    code: "sh",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    flag_4X3: "flags/4x3/sh.svg",
  },
  { code: "kn", name: "Saint Kitts and Nevis", flag_4X3: "flags/4x3/kn.svg" },
  { code: "lc", name: "Saint Lucia", flag_4X3: "flags/4x3/lc.svg" },
  { code: "mf", name: "Saint Martin", flag_4X3: "flags/4x3/mf.svg" },
  {
    code: "pm",
    name: "Saint Pierre and Miquelon",
    flag_4X3: "flags/4x3/pm.svg",
  },
  {
    code: "vc",
    name: "Saint Vincent and the Grenadines",
    flag_4X3: "flags/4x3/vc.svg",
  },
  { code: "ws", name: "Samoa", flag_4X3: "flags/4x3/ws.svg" },
  { code: "sm", name: "San Marino", flag_4X3: "flags/4x3/sm.svg" },
  { code: "st", name: "Sao Tome and Principe", flag_4X3: "flags/4x3/st.svg" },
  { code: "sa", name: "Saudi Arabia", flag_4X3: "flags/4x3/sa.svg" },
  { code: "gb-sct", name: "Scotland", flag_4X3: "flags/4x3/gb-sct.svg" },
  { code: "sn", name: "Senegal", flag_4X3: "flags/4x3/sn.svg" },
  { code: "rs", name: "Serbia", flag_4X3: "flags/4x3/rs.svg" },
  { code: "sc", name: "Seychelles", flag_4X3: "flags/4x3/sc.svg" },
  { code: "sl", name: "Sierra Leone", flag_4X3: "flags/4x3/sl.svg" },
  { code: "sg", name: "Singapore", flag_4X3: "flags/4x3/sg.svg" },
  { code: "sx", name: "Sint Maarten", flag_4X3: "flags/4x3/sx.svg" },
  { code: "sk", name: "Slovakia", flag_4X3: "flags/4x3/sk.svg" },
  { code: "si", name: "Slovenia", flag_4X3: "flags/4x3/si.svg" },
  { code: "sb", name: "Solomon Islands", flag_4X3: "flags/4x3/sb.svg" },
  { code: "so", name: "Somalia", flag_4X3: "flags/4x3/so.svg" },
  { code: "za", name: "South Africa", flag_4X3: "flags/4x3/za.svg" },
  {
    code: "gs",
    name: "South Georgia and the South Sandwich Islands",
    flag_4X3: "flags/4x3/gs.svg",
  },
  { code: "kr", name: "South Korea", flag_4X3: "flags/4x3/kr.svg" },
  { code: "ss", name: "South Sudan", flag_4X3: "flags/4x3/ss.svg" },
  { code: "es", name: "Spain", flag_4X3: "flags/4x3/es.svg" },
  { code: "lk", name: "Sri Lanka", flag_4X3: "flags/4x3/lk.svg" },
  { code: "ps", name: "State of Palestine", flag_4X3: "flags/4x3/ps.svg" },
  { code: "sd", name: "Sudan", flag_4X3: "flags/4x3/sd.svg" },
  { code: "sr", name: "Suriname", flag_4X3: "flags/4x3/sr.svg" },
  { code: "sj", name: "Svalbard and Jan Mayen", flag_4X3: "flags/4x3/sj.svg" },
  { code: "se", name: "Sweden", flag_4X3: "flags/4x3/se.svg" },
  { code: "ch", name: "Switzerland", flag_4X3: "flags/4x3/ch.svg" },
  { code: "sy", name: "Syria", flag_4X3: "flags/4x3/sy.svg" },
  { code: "tw", name: "Taiwan", flag_4X3: "flags/4x3/tw.svg" },
  { code: "tj", name: "Tajikistan", flag_4X3: "flags/4x3/tj.svg" },
  { code: "tz", name: "Tanzania", flag_4X3: "flags/4x3/tz.svg" },
  { code: "th", name: "Thailand", flag_4X3: "flags/4x3/th.svg" },
  { code: "tl", name: "Timor-Leste", flag_4X3: "flags/4x3/tl.svg" },
  { code: "tg", name: "Togo", flag_4X3: "flags/4x3/tg.svg" },
  { code: "tk", name: "Tokelau", flag_4X3: "flags/4x3/tk.svg" },
  { code: "to", name: "Tonga", flag_4X3: "flags/4x3/to.svg" },
  { code: "tt", name: "Trinidad and Tobago", flag_4X3: "flags/4x3/tt.svg" },
  { code: "ta", name: "Tristan da Cunha", flag_4X3: "flags/4x3/ta.svg" },
  { code: "tn", name: "Tunisia", flag_4X3: "flags/4x3/tn.svg" },
  { code: "tr", name: "Turkey", flag_4X3: "flags/4x3/tr.svg" },
  { code: "tm", name: "Turkmenistan", flag_4X3: "flags/4x3/tm.svg" },
  {
    code: "tc",
    name: "Turks and Caicos Islands",
    flag_4X3: "flags/4x3/tc.svg",
  },
  { code: "tv", name: "Tuvalu", flag_4X3: "flags/4x3/tv.svg" },
  { code: "ug", name: "Uganda", flag_4X3: "flags/4x3/ug.svg" },
  { code: "ua", name: "Ukraine", flag_4X3: "flags/4x3/ua.svg" },
  { code: "ae", name: "United Arab Emirates", flag_4X3: "flags/4x3/ae.svg" },
  { code: "gb", name: "United Kingdom", flag_4X3: "flags/4x3/gb.svg" },
  { code: "un", name: "United Nations", flag_4X3: "flags/4x3/un.svg" },
  {
    code: "um",
    name: "United States Minor Outlying Islands",
    flag_4X3: "flags/4x3/um.svg",
  },
  {
    code: "us",
    name: "United States of America",
    flag_4X3: "flags/4x3/us.svg",
  },
  { code: "xx", name: "Unknown", flag_4X3: "flags/4x3/xx.svg" },
  { code: "uy", name: "Uruguay", flag_4X3: "flags/4x3/uy.svg" },
  { code: "uz", name: "Uzbekistan", flag_4X3: "flags/4x3/uz.svg" },
  { code: "vu", name: "Vanuatu", flag_4X3: "flags/4x3/vu.svg" },
  { code: "ve", name: "Venezuela", flag_4X3: "flags/4x3/ve.svg" },
  { code: "vn", name: "Vietnam", flag_4X3: "flags/4x3/vn.svg" },
  {
    code: "vg",
    name: "Virgin Islands (British)",
    flag_4X3: "flags/4x3/vg.svg",
  },
  { code: "vi", name: "Virgin Islands (U.S.)", flag_4X3: "flags/4x3/vi.svg" },
  { code: "gb-wls", name: "Wales", flag_4X3: "flags/4x3/gb-wls.svg" },
  { code: "wf", name: "Wallis and Futuna", flag_4X3: "flags/4x3/wf.svg" },
  { code: "eh", name: "Western Sahara", flag_4X3: "flags/4x3/eh.svg" },
  { code: "ye", name: "Yemen", flag_4X3: "flags/4x3/ye.svg" },
  { code: "zm", name: "Zambia", flag_4X3: "flags/4x3/zm.svg" },
  { code: "zw", name: "Zimbabwe", flag_4X3: "flags/4x3/zw.svg" },
];
