const getCountryFlag = function getCountryFlag(country: string) {
  country = country?.toLowerCase();
  const nations = countries.filter((v) => {
    return (
      v.name?.toLowerCase() === country || v.code?.toLowerCase() === country
    );
  });
  let image = null;
  if (nations.length > 0) {
    image = require("./../assets/images/flag-icons-main/" +
      nations[0].flag_4X3);
  }
  return image;
};

export default getCountryFlag;

export const countries: {
  code: string;
  capital: string;
  name: string;
  flag_4X3: string;
}[] = [
  {
    code: "af",
    capital: "Kabul",
    name: "Afghanistan",
    flag_4X3: "flags/4x3/af.svg",
  },
  {
    code: "ax",
    capital: "Mariehamn",
    name: "Aland Islands",
    flag_4X3: "flags/4x3/ax.svg",
  },
  {
    code: "al",
    capital: "Tirana",
    name: "Albania",
    flag_4X3: "flags/4x3/al.svg",
  },
  {
    code: "dz",
    capital: "Algiers",
    name: "Algeria",
    flag_4X3: "flags/4x3/dz.svg",
  },
  {
    code: "as",
    capital: "Pago Pago",
    name: "American Samoa",
    flag_4X3: "flags/4x3/as.svg",
  },
  {
    code: "ad",
    capital: "Andorra la Vella",
    name: "Andorra",
    flag_4X3: "flags/4x3/ad.svg",
  },
  {
    code: "ao",
    capital: "Luanda",
    name: "Angola",
    flag_4X3: "flags/4x3/ao.svg",
  },
  {
    code: "ai",
    capital: "The Valley",
    name: "Anguilla",
    flag_4X3: "flags/4x3/ai.svg",
  },
  { code: "aq", capital: "", name: "Antarctica", flag_4X3: "flags/4x3/aq.svg" },
  {
    code: "ag",
    capital: "St. John's",
    name: "Antigua and Barbuda",
    flag_4X3: "flags/4x3/ag.svg",
  },
  {
    code: "ar",
    capital: "Buenos Aires",
    name: "Argentina",
    flag_4X3: "flags/4x3/ar.svg",
  },
  {
    code: "am",
    capital: "Yerevan",
    name: "Armenia",
    flag_4X3: "flags/4x3/am.svg",
  },
  {
    code: "aw",
    capital: "Oranjestad",
    name: "Aruba",
    flag_4X3: "flags/4x3/aw.svg",
  },
  {
    code: "ac",
    capital: "Georgetown",
    name: "Ascension Island",
    flag_4X3: "flags/4x3/ac.svg",
  },
  {
    code: "au",
    capital: "Canberra",
    name: "Australia",
    flag_4X3: "flags/4x3/au.svg",
  },
  {
    code: "at",
    capital: "Vienna",
    name: "Austria",
    flag_4X3: "flags/4x3/at.svg",
  },
  {
    code: "az",
    capital: "Baku",
    name: "Azerbaijan",
    flag_4X3: "flags/4x3/az.svg",
  },
  {
    code: "bs",
    capital: "Nassau",
    name: "Bahamas",
    flag_4X3: "flags/4x3/bs.svg",
  },
  {
    code: "bh",
    capital: "Manama",
    name: "Bahrain",
    flag_4X3: "flags/4x3/bh.svg",
  },
  {
    code: "bd",
    capital: "Dhaka",
    name: "Bangladesh",
    flag_4X3: "flags/4x3/bd.svg",
  },
  {
    code: "bb",
    capital: "Bridgetown",
    name: "Barbados",
    flag_4X3: "flags/4x3/bb.svg",
  },
  {
    code: "by",
    capital: "Minsk",
    name: "Belarus",
    flag_4X3: "flags/4x3/by.svg",
  },
  {
    code: "be",
    capital: "Brussels",
    name: "Belgium",
    flag_4X3: "flags/4x3/be.svg",
  },
  {
    code: "bz",
    capital: "Belmopan",
    name: "Belize",
    flag_4X3: "flags/4x3/bz.svg",
  },
  {
    code: "bj",
    capital: "Porto-Novo",
    name: "Benin",
    flag_4X3: "flags/4x3/bj.svg",
  },
  {
    code: "bm",
    capital: "Hamilton",
    name: "Bermuda",
    flag_4X3: "flags/4x3/bm.svg",
  },
  {
    code: "bt",
    capital: "Thimphu",
    name: "Bhutan",
    flag_4X3: "flags/4x3/bt.svg",
  },
  {
    code: "bo",
    capital: "Sucre",
    name: "Bolivia",
    flag_4X3: "flags/4x3/bo.svg",
  },
  {
    code: "bq",
    capital: "Kralendijk",
    name: "Bonaire, Sint Eustatius and Saba",
    flag_4X3: "flags/4x3/bq.svg",
  },
  {
    code: "ba",
    capital: "Sarajevo",
    name: "Bosnia and Herzegovina",
    flag_4X3: "flags/4x3/ba.svg",
  },
  {
    code: "bw",
    capital: "Gaborone",
    name: "Botswana",
    flag_4X3: "flags/4x3/bw.svg",
  },
  {
    code: "bv",
    capital: "",
    name: "Bouvet Island",
    flag_4X3: "flags/4x3/bv.svg",
  },
  {
    code: "br",
    capital: "Brasília",
    name: "Brazil",
    flag_4X3: "flags/4x3/br.svg",
  },
  {
    code: "io",
    capital: "Diego Garcia",
    name: "British Indian Ocean Territory",
    flag_4X3: "flags/4x3/io.svg",
  },
  {
    code: "bn",
    capital: "Bandar Seri Begawan",
    name: "Brunei Darussalam",
    flag_4X3: "flags/4x3/bn.svg",
  },
  {
    code: "bg",
    capital: "Sofia",
    name: "Bulgaria",
    flag_4X3: "flags/4x3/bg.svg",
  },
  {
    code: "bf",
    capital: "Ouagadougou",
    name: "Burkina Faso",
    flag_4X3: "flags/4x3/bf.svg",
  },
  {
    code: "bi",
    capital: "Bujumbura",
    name: "Burundi",
    flag_4X3: "flags/4x3/bi.svg",
  },
  {
    code: "cv",
    capital: "Praia",
    name: "Cabo Verde",
    flag_4X3: "flags/4x3/cv.svg",
  },
  {
    code: "kh",
    capital: "Phnom Penh",
    name: "Cambodia",
    flag_4X3: "flags/4x3/kh.svg",
  },
  {
    code: "cm",
    capital: "Yaoundé",
    name: "Cameroon",
    flag_4X3: "flags/4x3/cm.svg",
  },
  {
    code: "ca",
    capital: "Ottawa",
    name: "Canada",
    flag_4X3: "flags/4x3/ca.svg",
  },
  {
    code: "ic",
    capital: "",
    name: "Canary Islands",
    flag_4X3: "flags/4x3/ic.svg",
  },
  {
    code: "es-ct",
    capital: "",
    name: "Catalonia",
    flag_4X3: "flags/4x3/es-ct.svg",
  },
  {
    code: "es-pv",
    capital: "",
    name: "Basque Country",
    flag_4X3: "flags/4x3/es-pv.svg",
  },
  {
    code: "ky",
    capital: "George Town",
    name: "Cayman Islands",
    flag_4X3: "flags/4x3/ky.svg",
  },
  {
    code: "cf",
    capital: "Bangui",
    name: "Central African Republic",
    flag_4X3: "flags/4x3/cf.svg",
  },
  {
    code: "cefta",
    capital: "",
    name: "Central European Free Trade Agreement",
    flag_4X3: "flags/4x3/cefta.svg",
  },
  {
    code: "ea",
    capital: "",
    name: "Ceuta & Melilla",
    flag_4X3: "flags/4x3/ea.svg",
  },
  {
    code: "td",
    capital: "N'Djamena",
    name: "Chad",
    flag_4X3: "flags/4x3/td.svg",
  },
  {
    code: "cl",
    capital: "Santiago",
    name: "Chile",
    flag_4X3: "flags/4x3/cl.svg",
  },
  {
    code: "cn",
    capital: "Beijing",
    name: "China",
    flag_4X3: "flags/4x3/cn.svg",
  },
  {
    code: "cx",
    capital: "Flying Fish Cove",
    name: "Christmas Island",
    flag_4X3: "flags/4x3/cx.svg",
  },
  {
    code: "cp",
    capital: "",
    name: "Clipperton Island",
    flag_4X3: "flags/4x3/cp.svg",
  },
  {
    code: "cc",
    capital: "West Island",
    name: "Cocos (Keeling) Islands",
    flag_4X3: "flags/4x3/cc.svg",
  },
  {
    code: "co",
    capital: "Bogotá",
    name: "Colombia",
    flag_4X3: "flags/4x3/co.svg",
  },
  {
    code: "km",
    capital: "Moroni",
    name: "Comoros",
    flag_4X3: "flags/4x3/km.svg",
  },
  {
    code: "ck",
    capital: "Avarua",
    name: "Cook Islands",
    flag_4X3: "flags/4x3/ck.svg",
  },
  {
    code: "cr",
    capital: "San José",
    name: "Costa Rica",
    flag_4X3: "flags/4x3/cr.svg",
  },
  {
    code: "hr",
    capital: "Zagreb",
    name: "Croatia",
    flag_4X3: "flags/4x3/hr.svg",
  },
  { code: "cu", capital: "Havana", name: "Cuba", flag_4X3: "flags/4x3/cu.svg" },
  {
    code: "cw",
    capital: "Willemstad",
    name: "Curaçao",
    flag_4X3: "flags/4x3/cw.svg",
  },
  {
    code: "cy",
    capital: "Nicosia",
    name: "Cyprus",
    flag_4X3: "flags/4x3/cy.svg",
  },
  {
    code: "cz",
    capital: "Prague",
    name: "Czech Republic",
    flag_4X3: "flags/4x3/cz.svg",
  },
  {
    code: "ci",
    capital: "Yamoussoukro",
    name: "Côte d'Ivoire",
    flag_4X3: "flags/4x3/ci.svg",
  },
  {
    code: "cd",
    capital: "Kinshasa",
    name: "Democratic Republic of the Congo",
    flag_4X3: "flags/4x3/cd.svg",
  },
  {
    code: "dk",
    capital: "Copenhagen",
    name: "Denmark",
    flag_4X3: "flags/4x3/dk.svg",
  },
  {
    code: "dg",
    capital: "",
    name: "Diego Garcia",
    flag_4X3: "flags/4x3/dg.svg",
  },
  {
    code: "dj",
    capital: "Djibouti",
    name: "Djibouti",
    flag_4X3: "flags/4x3/dj.svg",
  },
  {
    code: "dm",
    capital: "Roseau",
    name: "Dominica",
    flag_4X3: "flags/4x3/dm.svg",
  },
  {
    code: "do",
    capital: "Santo Domingo",
    name: "Dominican Republic",
    flag_4X3: "flags/4x3/do.svg",
  },
  {
    code: "ec",
    capital: "Quito",
    name: "Ecuador",
    flag_4X3: "flags/4x3/ec.svg",
  },
  { code: "eg", capital: "Cairo", name: "Egypt", flag_4X3: "flags/4x3/eg.svg" },
  {
    code: "sv",
    capital: "San Salvador",
    name: "El Salvador",
    flag_4X3: "flags/4x3/sv.svg",
  },
  {
    code: "gb-eng",
    capital: "London",
    name: "England",
    flag_4X3: "flags/4x3/gb-eng.svg",
  },
  {
    code: "gq",
    capital: "Malabo",
    name: "Equatorial Guinea",
    flag_4X3: "flags/4x3/gq.svg",
  },
  {
    code: "er",
    capital: "Asmara",
    name: "Eritrea",
    flag_4X3: "flags/4x3/er.svg",
  },
  {
    code: "ee",
    capital: "Tallinn",
    name: "Estonia",
    flag_4X3: "flags/4x3/ee.svg",
  },
  {
    code: "sz",
    capital: "Lobamba, Mbabane",
    name: "Eswatini",
    flag_4X3: "flags/4x3/sz.svg",
  },
  {
    code: "et",
    capital: "Addis Ababa",
    name: "Ethiopia",
    flag_4X3: "flags/4x3/et.svg",
  },
  { code: "eu", capital: "", name: "Europe", flag_4X3: "flags/4x3/eu.svg" },
  {
    code: "fk",
    capital: "Stanley",
    name: "Falkland Islands",
    flag_4X3: "flags/4x3/fk.svg",
  },
  {
    code: "fo",
    capital: "Tórshavn",
    name: "Faroe Islands",
    flag_4X3: "flags/4x3/fo.svg",
  },
  {
    code: "fm",
    capital: "Palikir",
    name: "Federated States of Micronesia",
    flag_4X3: "flags/4x3/fm.svg",
  },
  { code: "fj", capital: "Suva", name: "Fiji", flag_4X3: "flags/4x3/fj.svg" },
  {
    code: "fi",
    capital: "Helsinki",
    name: "Finland",
    flag_4X3: "flags/4x3/fi.svg",
  },
  {
    code: "fr",
    capital: "Paris",
    name: "France",
    flag_4X3: "flags/4x3/fr.svg",
  },
  {
    code: "gf",
    capital: "Cayenne",
    name: "French Guiana",
    flag_4X3: "flags/4x3/gf.svg",
  },
  {
    code: "pf",
    capital: "Papeete",
    name: "French Polynesia",
    flag_4X3: "flags/4x3/pf.svg",
  },
  {
    code: "tf",
    capital: "Saint-Pierre, Réunion",
    name: "French Southern Territories",
    flag_4X3: "flags/4x3/tf.svg",
  },
  {
    code: "ga",
    capital: "Libreville",
    name: "Gabon",
    flag_4X3: "flags/4x3/ga.svg",
  },
  {
    code: "es-ga",
    capital: "",
    name: "Galicia",
    flag_4X3: "flags/4x3/es-ga.svg",
  },
  {
    code: "gm",
    capital: "Banjul",
    name: "Gambia",
    flag_4X3: "flags/4x3/gm.svg",
  },
  {
    code: "ge",
    capital: "Tbilisi",
    name: "Georgia",
    flag_4X3: "flags/4x3/ge.svg",
  },
  {
    code: "de",
    capital: "Berlin",
    name: "Germany",
    flag_4X3: "flags/4x3/de.svg",
  },
  { code: "gh", capital: "Accra", name: "Ghana", flag_4X3: "flags/4x3/gh.svg" },
  {
    code: "gi",
    capital: "Gibraltar",
    name: "Gibraltar",
    flag_4X3: "flags/4x3/gi.svg",
  },
  {
    code: "gr",
    capital: "Athens",
    name: "Greece",
    flag_4X3: "flags/4x3/gr.svg",
  },
  {
    code: "gl",
    capital: "Nuuk",
    name: "Greenland",
    flag_4X3: "flags/4x3/gl.svg",
  },
  {
    code: "gd",
    capital: "St. George's",
    name: "Grenada",
    flag_4X3: "flags/4x3/gd.svg",
  },
  {
    code: "gp",
    capital: "Basse-Terre",
    name: "Guadeloupe",
    flag_4X3: "flags/4x3/gp.svg",
  },
  {
    code: "gu",
    capital: "Hagåtña",
    name: "Guam",
    flag_4X3: "flags/4x3/gu.svg",
  },
  {
    code: "gt",
    capital: "Guatemala City",
    name: "Guatemala",
    flag_4X3: "flags/4x3/gt.svg",
  },
  {
    code: "gg",
    capital: "Saint Peter Port",
    name: "Guernsey",
    flag_4X3: "flags/4x3/gg.svg",
  },
  {
    code: "gn",
    capital: "Conakry",
    name: "Guinea",
    flag_4X3: "flags/4x3/gn.svg",
  },
  {
    code: "gw",
    capital: "Bissau",
    name: "Guinea-Bissau",
    flag_4X3: "flags/4x3/gw.svg",
  },
  {
    code: "gy",
    capital: "Georgetown",
    name: "Guyana",
    flag_4X3: "flags/4x3/gy.svg",
  },
  {
    code: "ht",
    capital: "Port-au-Prince",
    name: "Haiti",
    flag_4X3: "flags/4x3/ht.svg",
  },
  {
    code: "hm",
    capital: "",
    name: "Heard Island and McDonald Islands",
    flag_4X3: "flags/4x3/hm.svg",
  },
  {
    code: "va",
    capital: "Vatican City",
    name: "Holy See",
    flag_4X3: "flags/4x3/va.svg",
  },
  {
    code: "hn",
    capital: "Tegucigalpa",
    name: "Honduras",
    flag_4X3: "flags/4x3/hn.svg",
  },
  {
    code: "hk",
    capital: "Hong Kong",
    name: "Hong Kong",
    flag_4X3: "flags/4x3/hk.svg",
  },
  {
    code: "hu",
    capital: "Budapest",
    name: "Hungary",
    flag_4X3: "flags/4x3/hu.svg",
  },
  {
    code: "is",
    capital: "Reykjavik",
    name: "Iceland",
    flag_4X3: "flags/4x3/is.svg",
  },
  {
    code: "in",
    capital: "New Delhi",
    name: "India",
    flag_4X3: "flags/4x3/in.svg",
  },
  {
    code: "id",
    capital: "Jakarta",
    name: "Indonesia",
    flag_4X3: "flags/4x3/id.svg",
  },
  { code: "ir", capital: "Tehran", name: "Iran", flag_4X3: "flags/4x3/ir.svg" },
  {
    code: "iq",
    capital: "Baghdad",
    name: "Iraq",
    flag_4X3: "flags/4x3/iq.svg",
  },
  {
    code: "ie",
    capital: "Dublin",
    name: "Ireland",
    flag_4X3: "flags/4x3/ie.svg",
  },
  {
    code: "im",
    capital: "Douglas",
    name: "Isle of Man",
    flag_4X3: "flags/4x3/im.svg",
  },
  {
    code: "il",
    capital: "Jerusalem",
    name: "Israel",
    flag_4X3: "flags/4x3/il.svg",
  },
  { code: "it", capital: "Rome", name: "Italy", flag_4X3: "flags/4x3/it.svg" },
  {
    code: "jm",
    capital: "Kingston",
    name: "Jamaica",
    flag_4X3: "flags/4x3/jm.svg",
  },
  { code: "jp", capital: "Tokyo", name: "Japan", flag_4X3: "flags/4x3/jp.svg" },
  {
    code: "je",
    capital: "Saint Helier",
    name: "Jersey",
    flag_4X3: "flags/4x3/je.svg",
  },
  {
    code: "jo",
    capital: "Amman",
    name: "Jordan",
    flag_4X3: "flags/4x3/jo.svg",
  },
  {
    code: "kz",
    capital: "Astana",
    name: "Kazakhstan",
    flag_4X3: "flags/4x3/kz.svg",
  },
  {
    code: "ke",
    capital: "Nairobi",
    name: "Kenya",
    flag_4X3: "flags/4x3/ke.svg",
  },
  {
    code: "ki",
    capital: "South Tarawa",
    name: "Kiribati",
    flag_4X3: "flags/4x3/ki.svg",
  },
  {
    code: "xk",
    capital: "Pristina",
    name: "Kosovo",
    flag_4X3: "flags/4x3/xk.svg",
  },
  {
    code: "kw",
    capital: "Kuwait City",
    name: "Kuwait",
    flag_4X3: "flags/4x3/kw.svg",
  },
  {
    code: "kg",
    capital: "Bishkek",
    name: "Kyrgyzstan",
    flag_4X3: "flags/4x3/kg.svg",
  },
  {
    code: "la",
    capital: "Vientiane",
    name: "Laos",
    flag_4X3: "flags/4x3/la.svg",
  },
  { code: "lv", capital: "Riga", name: "Latvia", flag_4X3: "flags/4x3/lv.svg" },
  {
    code: "lb",
    capital: "Beirut",
    name: "Lebanon",
    flag_4X3: "flags/4x3/lb.svg",
  },
  {
    code: "ls",
    capital: "Maseru",
    name: "Lesotho",
    flag_4X3: "flags/4x3/ls.svg",
  },
  {
    code: "lr",
    capital: "Monrovia",
    name: "Liberia",
    flag_4X3: "flags/4x3/lr.svg",
  },
  {
    code: "ly",
    capital: "Tripoli",
    name: "Libya",
    flag_4X3: "flags/4x3/ly.svg",
  },
  {
    code: "li",
    capital: "Vaduz",
    name: "Liechtenstein",
    flag_4X3: "flags/4x3/li.svg",
  },
  {
    code: "lt",
    capital: "Vilnius",
    name: "Lithuania",
    flag_4X3: "flags/4x3/lt.svg",
  },
  {
    code: "lu",
    capital: "Luxembourg City",
    name: "Luxembourg",
    flag_4X3: "flags/4x3/lu.svg",
  },
  { code: "mo", capital: "Macau", name: "Macau", flag_4X3: "flags/4x3/mo.svg" },
  {
    code: "mg",
    capital: "Antananarivo",
    name: "Madagascar",
    flag_4X3: "flags/4x3/mg.svg",
  },
  {
    code: "mw",
    capital: "Lilongwe",
    name: "Malawi",
    flag_4X3: "flags/4x3/mw.svg",
  },
  {
    code: "my",
    capital: "Kuala Lumpur",
    name: "Malaysia",
    flag_4X3: "flags/4x3/my.svg",
  },
  {
    code: "mv",
    capital: "Malé",
    name: "Maldives",
    flag_4X3: "flags/4x3/mv.svg",
  },
  { code: "ml", capital: "Bamako", name: "Mali", flag_4X3: "flags/4x3/ml.svg" },
  {
    code: "mt",
    capital: "Valletta",
    name: "Malta",
    flag_4X3: "flags/4x3/mt.svg",
  },
  {
    code: "mh",
    capital: "Majuro",
    name: "Marshall Islands",
    flag_4X3: "flags/4x3/mh.svg",
  },
  {
    code: "mq",
    capital: "Fort-de-France",
    name: "Martinique",
    flag_4X3: "flags/4x3/mq.svg",
  },
  {
    code: "mr",
    capital: "Nouakchott",
    name: "Mauritania",
    flag_4X3: "flags/4x3/mr.svg",
  },
  {
    code: "mu",
    capital: "Port Louis",
    name: "Mauritius",
    flag_4X3: "flags/4x3/mu.svg",
  },
  {
    code: "yt",
    capital: "Mamoudzou",
    name: "Mayotte",
    flag_4X3: "flags/4x3/yt.svg",
  },
  {
    code: "mx",
    capital: "Mexico City",
    name: "Mexico",
    flag_4X3: "flags/4x3/mx.svg",
  },
  {
    code: "md",
    capital: "Chișinău",
    name: "Moldova",
    flag_4X3: "flags/4x3/md.svg",
  },
  {
    code: "mc",
    capital: "Monaco",
    name: "Monaco",
    flag_4X3: "flags/4x3/mc.svg",
  },
  {
    code: "mn",
    capital: "Ulaanbaatar",
    name: "Mongolia",
    flag_4X3: "flags/4x3/mn.svg",
  },
  {
    code: "me",
    capital: "Podgorica",
    name: "Montenegro",
    flag_4X3: "flags/4x3/me.svg",
  },
  {
    code: "ms",
    capital: "Little Bay, Brades, Plymouth",
    name: "Montserrat",
    flag_4X3: "flags/4x3/ms.svg",
  },
  {
    code: "ma",
    capital: "Rabat",
    name: "Morocco",
    flag_4X3: "flags/4x3/ma.svg",
  },
  {
    code: "mz",
    capital: "Maputo",
    name: "Mozambique",
    flag_4X3: "flags/4x3/mz.svg",
  },
  {
    code: "mm",
    capital: "Naypyidaw",
    name: "Myanmar",
    flag_4X3: "flags/4x3/mm.svg",
  },
  {
    code: "na",
    capital: "Windhoek",
    name: "Namibia",
    flag_4X3: "flags/4x3/na.svg",
  },
  {
    code: "nr",
    capital: "Yaren District",
    name: "Nauru",
    flag_4X3: "flags/4x3/nr.svg",
  },
  {
    code: "np",
    capital: "Kathmandu",
    name: "Nepal",
    flag_4X3: "flags/4x3/np.svg",
  },
  {
    code: "nl",
    capital: "Amsterdam",
    name: "Netherlands",
    flag_4X3: "flags/4x3/nl.svg",
  },
  {
    code: "nc",
    capital: "Nouméa",
    name: "New Caledonia",
    flag_4X3: "flags/4x3/nc.svg",
  },
  {
    code: "nz",
    capital: "Wellington",
    name: "New Zealand",
    flag_4X3: "flags/4x3/nz.svg",
  },
  {
    code: "ni",
    capital: "Managua",
    name: "Nicaragua",
    flag_4X3: "flags/4x3/ni.svg",
  },
  {
    code: "ne",
    capital: "Niamey",
    name: "Niger",
    flag_4X3: "flags/4x3/ne.svg",
  },
  {
    code: "ng",
    capital: "Abuja",
    name: "Nigeria",
    flag_4X3: "flags/4x3/ng.svg",
  },
  { code: "nu", capital: "Alofi", name: "Niue", flag_4X3: "flags/4x3/nu.svg" },
  {
    code: "nf",
    capital: "Kingston",
    name: "Norfolk Island",
    flag_4X3: "flags/4x3/nf.svg",
  },
  {
    code: "kp",
    capital: "Pyongyang",
    name: "North Korea",
    flag_4X3: "flags/4x3/kp.svg",
  },
  {
    code: "mk",
    capital: "Skopje",
    name: "North Macedonia",
    flag_4X3: "flags/4x3/mk.svg",
  },
  {
    code: "gb-nir",
    capital: "Belfast",
    name: "Northern Ireland",
    flag_4X3: "flags/4x3/gb-nir.svg",
  },
  {
    code: "mp",
    capital: "Saipan",
    name: "Northern Mariana Islands",
    flag_4X3: "flags/4x3/mp.svg",
  },
  { code: "no", capital: "Oslo", name: "Norway", flag_4X3: "flags/4x3/no.svg" },
  { code: "om", capital: "Muscat", name: "Oman", flag_4X3: "flags/4x3/om.svg" },
  {
    code: "pk",
    capital: "Islamabad",
    name: "Pakistan",
    flag_4X3: "flags/4x3/pk.svg",
  },
  {
    code: "pw",
    capital: "Ngerulmud",
    name: "Palau",
    flag_4X3: "flags/4x3/pw.svg",
  },
  {
    code: "pa",
    capital: "Panama City",
    name: "Panama",
    flag_4X3: "flags/4x3/pa.svg",
  },
  {
    code: "pg",
    capital: "Port Moresby",
    name: "Papua New Guinea",
    flag_4X3: "flags/4x3/pg.svg",
  },
  {
    code: "py",
    capital: "Asunción",
    name: "Paraguay",
    flag_4X3: "flags/4x3/py.svg",
  },
  { code: "pe", capital: "Lima", name: "Peru", flag_4X3: "flags/4x3/pe.svg" },
  {
    code: "ph",
    capital: "Manila",
    name: "Philippines",
    flag_4X3: "flags/4x3/ph.svg",
  },
  {
    code: "pn",
    capital: "Adamstown",
    name: "Pitcairn",
    flag_4X3: "flags/4x3/pn.svg",
  },
  {
    code: "pl",
    capital: "Warsaw",
    name: "Poland",
    flag_4X3: "flags/4x3/pl.svg",
  },
  {
    code: "pt",
    capital: "Lisbon",
    name: "Portugal",
    flag_4X3: "flags/4x3/pt.svg",
  },
  {
    code: "pr",
    capital: "San Juan",
    name: "Puerto Rico",
    flag_4X3: "flags/4x3/pr.svg",
  },
  { code: "qa", capital: "Doha", name: "Qatar", flag_4X3: "flags/4x3/qa.svg" },
  {
    code: "cg",
    capital: "Brazzaville",
    name: "Republic of the Congo",
    flag_4X3: "flags/4x3/cg.svg",
  },
  {
    code: "ro",
    capital: "Bucharest",
    name: "Romania",
    flag_4X3: "flags/4x3/ro.svg",
  },
  {
    code: "ru",
    capital: "Moscow",
    name: "Russia",
    flag_4X3: "flags/4x3/ru.svg",
  },
  {
    code: "rw",
    capital: "Kigali",
    name: "Rwanda",
    flag_4X3: "flags/4x3/rw.svg",
  },
  {
    code: "re",
    capital: "Saint-Denis",
    name: "Réunion",
    flag_4X3: "flags/4x3/re.svg",
  },
  {
    code: "bl",
    capital: "Gustavia",
    name: "Saint Barthélemy",
    flag_4X3: "flags/4x3/bl.svg",
  },
  {
    code: "sh",
    capital: "Jamestown",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    flag_4X3: "flags/4x3/sh.svg",
  },
  {
    code: "kn",
    capital: "Basseterre",
    name: "Saint Kitts and Nevis",
    flag_4X3: "flags/4x3/kn.svg",
  },
  {
    code: "lc",
    capital: "Castries",
    name: "Saint Lucia",
    flag_4X3: "flags/4x3/lc.svg",
  },
  {
    code: "mf",
    capital: "Marigot",
    name: "Saint Martin",
    flag_4X3: "flags/4x3/mf.svg",
  },
  {
    code: "pm",
    capital: "Saint-Pierre",
    name: "Saint Pierre and Miquelon",
    flag_4X3: "flags/4x3/pm.svg",
  },
  {
    code: "vc",
    capital: "Kingstown",
    name: "Saint Vincent and the Grenadines",
    flag_4X3: "flags/4x3/vc.svg",
  },
  { code: "ws", capital: "Apia", name: "Samoa", flag_4X3: "flags/4x3/ws.svg" },
  {
    code: "sm",
    capital: "San Marino",
    name: "San Marino",
    flag_4X3: "flags/4x3/sm.svg",
  },
  {
    code: "st",
    capital: "São Tomé",
    name: "Sao Tome and Principe",
    flag_4X3: "flags/4x3/st.svg",
  },
  {
    code: "sa",
    capital: "Riyadh",
    name: "Saudi Arabia",
    flag_4X3: "flags/4x3/sa.svg",
  },
  {
    code: "gb-sct",
    capital: "Edinburgh",
    name: "Scotland",
    flag_4X3: "flags/4x3/gb-sct.svg",
  },
  {
    code: "sn",
    capital: "Dakar",
    name: "Senegal",
    flag_4X3: "flags/4x3/sn.svg",
  },
  {
    code: "rs",
    capital: "Belgrade",
    name: "Serbia",
    flag_4X3: "flags/4x3/rs.svg",
  },
  {
    code: "sc",
    capital: "Victoria",
    name: "Seychelles",
    flag_4X3: "flags/4x3/sc.svg",
  },
  {
    code: "sl",
    capital: "Freetown",
    name: "Sierra Leone",
    flag_4X3: "flags/4x3/sl.svg",
  },
  {
    code: "sg",
    capital: "Singapore",
    name: "Singapore",
    flag_4X3: "flags/4x3/sg.svg",
  },
  {
    code: "sx",
    capital: "Philipsburg",
    name: "Sint Maarten",
    flag_4X3: "flags/4x3/sx.svg",
  },
  {
    code: "sk",
    capital: "Bratislava",
    name: "Slovakia",
    flag_4X3: "flags/4x3/sk.svg",
  },
  {
    code: "si",
    capital: "Ljubljana",
    name: "Slovenia",
    flag_4X3: "flags/4x3/si.svg",
  },
  {
    code: "sb",
    capital: "Honiara",
    name: "Solomon Islands",
    flag_4X3: "flags/4x3/sb.svg",
  },
  {
    code: "so",
    capital: "Mogadishu",
    name: "Somalia",
    flag_4X3: "flags/4x3/so.svg",
  },
  {
    code: "za",
    capital: "Pretoria",
    name: "South Africa",
    flag_4X3: "flags/4x3/za.svg",
  },
  {
    code: "gs",
    capital: "King Edward Point",
    name: "South Georgia and the South Sandwich Islands",
    flag_4X3: "flags/4x3/gs.svg",
  },
  {
    code: "kr",
    capital: "Seoul",
    name: "South Korea",
    flag_4X3: "flags/4x3/kr.svg",
  },
  {
    code: "ss",
    capital: "Juba",
    name: "South Sudan",
    flag_4X3: "flags/4x3/ss.svg",
  },
  {
    code: "es",
    capital: "Madrid",
    name: "Spain",
    flag_4X3: "flags/4x3/es.svg",
  },
  {
    code: "lk",
    capital: "Sri Jayawardenepura Kotte, Colombo",
    name: "Sri Lanka",
    flag_4X3: "flags/4x3/lk.svg",
  },
  {
    code: "ps",
    capital: "Ramallah",
    name: "State of Palestine",
    flag_4X3: "flags/4x3/ps.svg",
  },
  {
    code: "sd",
    capital: "Khartoum",
    name: "Sudan",
    flag_4X3: "flags/4x3/sd.svg",
  },
  {
    code: "sr",
    capital: "Paramaribo",
    name: "Suriname",
    flag_4X3: "flags/4x3/sr.svg",
  },
  {
    code: "sj",
    capital: "Longyearbyen",
    name: "Svalbard and Jan Mayen",
    flag_4X3: "flags/4x3/sj.svg",
  },
  {
    code: "se",
    capital: "Stockholm",
    name: "Sweden",
    flag_4X3: "flags/4x3/se.svg",
  },
  {
    code: "ch",
    capital: "Bern",
    name: "Switzerland",
    flag_4X3: "flags/4x3/ch.svg",
  },
  {
    code: "sy",
    capital: "Damascus",
    name: "Syria",
    flag_4X3: "flags/4x3/sy.svg",
  },
  {
    code: "tw",
    capital: "Taipei",
    name: "Taiwan",
    flag_4X3: "flags/4x3/tw.svg",
  },
  {
    code: "tj",
    capital: "Dushanbe",
    name: "Tajikistan",
    flag_4X3: "flags/4x3/tj.svg",
  },
  {
    code: "tz",
    capital: "Dodoma",
    name: "Tanzania",
    flag_4X3: "flags/4x3/tz.svg",
  },
  {
    code: "th",
    capital: "Bangkok",
    name: "Thailand",
    flag_4X3: "flags/4x3/th.svg",
  },
  {
    code: "tl",
    capital: "Dili",
    name: "Timor-Leste",
    flag_4X3: "flags/4x3/tl.svg",
  },
  { code: "tg", capital: "Lomé", name: "Togo", flag_4X3: "flags/4x3/tg.svg" },
  {
    code: "tk",
    capital: "Nukunonu, Atafu,Tokelau",
    name: "Tokelau",
    flag_4X3: "flags/4x3/tk.svg",
  },
  {
    code: "to",
    capital: "Nukuʻalofa",
    name: "Tonga",
    flag_4X3: "flags/4x3/to.svg",
  },
  {
    code: "tt",
    capital: "Port of Spain",
    name: "Trinidad and Tobago",
    flag_4X3: "flags/4x3/tt.svg",
  },
  {
    code: "ta",
    capital: "",
    name: "Tristan da Cunha",
    flag_4X3: "flags/4x3/ta.svg",
  },
  {
    code: "tn",
    capital: "Tunis",
    name: "Tunisia",
    flag_4X3: "flags/4x3/tn.svg",
  },
  {
    code: "tr",
    capital: "Ankara",
    name: "Turkey",
    flag_4X3: "flags/4x3/tr.svg",
  },
  {
    code: "tm",
    capital: "Ashgabat",
    name: "Turkmenistan",
    flag_4X3: "flags/4x3/tm.svg",
  },
  {
    code: "tc",
    capital: "Cockburn Town",
    name: "Turks and Caicos Islands",
    flag_4X3: "flags/4x3/tc.svg",
  },
  {
    code: "tv",
    capital: "Funafuti",
    name: "Tuvalu",
    flag_4X3: "flags/4x3/tv.svg",
  },
  {
    code: "ug",
    capital: "Kampala",
    name: "Uganda",
    flag_4X3: "flags/4x3/ug.svg",
  },
  {
    code: "ua",
    capital: "Kiev",
    name: "Ukraine",
    flag_4X3: "flags/4x3/ua.svg",
  },
  {
    code: "ae",
    capital: "Abu Dhabi",
    name: "United Arab Emirates",
    flag_4X3: "flags/4x3/ae.svg",
  },
  {
    code: "gb",
    capital: "London",
    name: "United Kingdom",
    flag_4X3: "flags/4x3/gb.svg",
  },
  {
    code: "un",
    capital: "",
    name: "United Nations",
    flag_4X3: "flags/4x3/un.svg",
  },
  {
    code: "um",
    capital: "Washington, D.C.",
    name: "United States Minor Outlying Islands",
    flag_4X3: "flags/4x3/um.svg",
  },
  {
    code: "us",
    capital: "Washington, D.C.",
    name: "United States of America",
    flag_4X3: "flags/4x3/us.svg",
  },
  { code: "xx", capital: "", name: "Unknown", flag_4X3: "flags/4x3/xx.svg" },
  {
    code: "uy",
    capital: "Montevideo",
    name: "Uruguay",
    flag_4X3: "flags/4x3/uy.svg",
  },
  {
    code: "uz",
    capital: "Tashkent",
    name: "Uzbekistan",
    flag_4X3: "flags/4x3/uz.svg",
  },
  {
    code: "vu",
    capital: "Port Vila",
    name: "Vanuatu",
    flag_4X3: "flags/4x3/vu.svg",
  },
  {
    code: "ve",
    capital: "Caracas",
    name: "Venezuela",
    flag_4X3: "flags/4x3/ve.svg",
  },
  {
    code: "vn",
    capital: "Hanoi",
    name: "Vietnam",
    flag_4X3: "flags/4x3/vn.svg",
  },
  {
    code: "vg",
    capital: "Road Town",
    name: "Virgin Islands (British)",
    flag_4X3: "flags/4x3/vg.svg",
  },
  {
    code: "vi",
    capital: "Charlotte Amalie",
    name: "Virgin Islands (U.S.)",
    flag_4X3: "flags/4x3/vi.svg",
  },
  {
    code: "gb-wls",
    capital: "Cardiff",
    name: "Wales",
    flag_4X3: "flags/4x3/gb-wls.svg",
  },
  {
    code: "wf",
    capital: "Mata-Utu",
    name: "Wallis and Futuna",
    flag_4X3: "flags/4x3/wf.svg",
  },
  {
    code: "eh",
    capital: "Laayoune",
    name: "Western Sahara",
    flag_4X3: "flags/4x3/eh.svg",
  },
  {
    code: "ye",
    capital: "Sana'a",
    name: "Yemen",
    flag_4X3: "flags/4x3/ye.svg",
  },
  {
    code: "zm",
    capital: "Lusaka",
    name: "Zambia",
    flag_4X3: "flags/4x3/zm.svg",
  },
  {
    code: "zw",
    capital: "Harare",
    name: "Zimbabwe",
    flag_4X3: "flags/4x3/zw.svg",
  },
];
